name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build: # Este é o nome do check ("build") que você adicionará na proteção de branch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21 # Ajuste para a versão do seu projeto (ex: 17, 21)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: ./mvnw clean verify # Usa o wrapper do Maven para compilar e rodar os testes
       
      
